services:

    marketing_suite.listener.kernel_response.add_test_header:
        class: numero2\MarketingSuiteBundle\EventListener\KernelResponse\TestHeaderListener
        arguments:
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 248 }

    marketing_suite.listener.kernel_response.add_health_check_header:
        class: numero2\MarketingSuiteBundle\EventListener\KernelResponse\HealthCheckHeaderListener
        arguments:
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 249 }

    marketing_suite.listener.menu.backend_sort_menu:
        class: numero2\MarketingSuiteBundle\EventListener\Menu\BackendSortMenuListener
        arguments:
            - '@security.helper'
            - '@contao.framework'
        tags:
            - { name: kernel.event_listener, event: contao.backend_menu_build, priority: -5 }

    marketing_suite.listener.menu.backend_custom_route:
        class: numero2\MarketingSuiteBundle\EventListener\Menu\BackendCustomRouteMenuListener
        arguments:
            - '@security.helper'
            - '@contao.framework'
        tags:
            - { name: kernel.event_listener, event: contao.backend_menu_build, priority: -5 }


    # Backwards compatibility for contao 4.4
    marketing_suite.listener.legacy_link_shortener:
        class: numero2\MarketingSuiteBundle\EventListener\KernelException\LinkShortenerRedirect
        arguments:
            - "@contao.routing.scope_matcher"
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 256 }
