services:

    marketing_suite.listener.kernel_response.add_test_header:
        class: numero2\MarketingSuiteBundle\EventListener\KernelResponse\TestHeaderListener
        arguments:
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 248 }

    marketing_suite.listener.kernel_response.add_health_check_header:
        class: numero2\MarketingSuiteBundle\EventListener\KernelResponse\HealthCheckHeaderListener
        arguments:
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 249 }


    marketing_suite.listener.legacy_link_shortener:
        class: numero2\MarketingSuiteBundle\EventListener\KernelException\LinkShortenerRedirect
        arguments:
            - "@contao.routing.scope_matcher"
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 256 }
