services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [setContainer, ['@Psr\Container\ContainerInterface']]

    marketing_suite.picker.link_shortener_provider:
        class: numero2\MarketingSuiteBundle\Picker\LinkShortenerPickerProvider
        arguments:
            - "@knp_menu.factory"
            - "@router"
            - '@translator'
        tags:
            - { name: contao.picker_provider, priority: 96 }

    marketing_suite.controller.link_shortener:
        class: numero2\MarketingSuiteBundle\Controller\LinkShortenerController
        tags:
            - { name: controller.service_arguments }

    marketing_suite.routing.router:
        class: Symfony\Cmf\Component\Routing\DynamicRouter
        arguments:
            - '@router.request_context'
            - '@marketing_suite.routing.nested_matcher'
            - '@marketing_suite.routing.page_url_generator'
            - ''
            - '@event_dispatcher'
            - '@marketing_suite.routing.route_provider'
        tags:
            - { name: router, priority: 80 }

    marketing_suite.routing.nested_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\NestedMatcher
        arguments:
            - '@marketing_suite.routing.route_provider'
            - '@marketing_suite.routing.final_matcher'

    marketing_suite.routing.final_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\UrlMatcher
        arguments:
            - '@marketing_suite.routing.dummy_collection'
            - '@marketing_suite.routing.dummy_context'

    marketing_suite.routing.dummy_context:
        class: Symfony\Component\Routing\RequestContext

    marketing_suite.routing.dummy_collection:
        class: Symfony\Component\Routing\RouteCollection

    marketing_suite.routing.route_provider:
        class: numero2\MarketingSuiteBundle\Routing\RouteProvider
        arguments:
            - '@contao.framework'
            - '@contao.routing.page_candidates'
            - '@contao.routing.page_registry'
            - '@marketing_suite.routing.ab_test_page_provider'
            - '@marketing_suite.routing.link_shortener_route_provider'

    marketing_suite.routing.ab_test_page_provider:
        class: numero2\MarketingSuiteBundle\Routing\ABTestPageRouteProvider
        arguments:
            - "@contao.framework"
            - "@contao.routing.route_provider"

    marketing_suite.routing.link_shortener_route_provider:
        class: numero2\MarketingSuiteBundle\Routing\LinkShortenerRouteProvider
        arguments:
            - "@contao.framework"

    marketing_suite.routing.page_url_generator:
        class: numero2\MarketingSuiteBundle\Routing\PageUrlGenerator
        arguments:
            - '@marketing_suite.routing.route_provider'
            - '@?contao.routing.page_registry'
            - '@?logger'

    marketing_suite.tracking.click_and_views:
        class: numero2\MarketingSuiteBundle\Tracking\ClickAndViews
        public: true
        arguments:
            - '@request_stack'

    marketing_suite.tracking.session:
        class: numero2\MarketingSuiteBundle\Tracking\Session
        public: true
        arguments:
            - '@request_stack'
            - '@contao.routing.scope_matcher'
            - '@contao.security.token_checker'
            - '@marketing_suite.util.cache_request'


    marketing_suite.twig.extension:
        class: numero2\MarketingSuiteBundle\Twig\Extension\MarketingSuiteExtension
        public: true


    marketing_suite.util.cache_request:
        class: numero2\MarketingSuiteBundle\Util\CacheRequestUtil
        public: true
        arguments:
            - '@request_stack'

    numero2\MarketingSuiteBundle\Controller\BackendController: ~

    numero2\MarketingSuiteBundle\Controller\Page\ABTestPageController:
        arguments:
            - '@contao.framework'
